version: "3.7"
services:
  fastapi_sample:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
      args:
        WORKDIR: /project
    volumes:
      - .:/project
      - ${USERPROFILE-~}/.ssh:/home/vscode/.ssh
    image: fastapi_sample-image
    container_name: fastapi_sample-container
    tty: true
    ports:
      - "8080:8080"
